GlobalPlanner:
  old_navfn_behavior: false # Do not mirror behaviour of navfn
  use_quadratic: true # Use the quadratic approximation of the potential
  use_dijkstra: true # Use dijkstra's algorithm, otherwise A* default
  use_grid_path: false # Create a path that follows the grid boundaries, otherwise use a gradient descent method

  allow_unknown: true # Allow planner to plan through unknown space, default true

  visualize_potential: false # Visualise the potential map

  default_tolerance: 0.1

  lethal_cost: 253 # Will not produce path if too low
  neutral_cost: 66 # Open space value
  cost_factor: 0.55 # Translates costs of inputs evenly over output range, needs tweaking for spread

TrajectoryPlannerROS:
  # Robot Configuration Parameters
  acc_lim_x: 2.5
  acc_lim_y: 2.5
  acc_lim_theta: 3.2
  max_vel_x: 1.0
  min_vel_x: 0.3
  max_vel_theta: 1.0
  min_vel_theta: -1.0
  min_in_place_vel_theta: 0.4
  escape_vel: -0.4
  holonomic_robot: true

  # The following parameters are only used if holonomic_robot is set to true:
  y_vels: [-0.3, -0.1, 0.1, 0.3]

  # Goal Tolerance Parameters
  yaw_goal_tolerance: 0.2
  xy_goal_tolerance: 0.3
  latch_xy_goal_tolerance: false

  # Forward Simulation Parameters
  sim_time: 1.55
  sim_granularity: 0.025
  angular_sim_granularity: 0.025
  vx_samples: 20
  vtheta_samples: 40
  # Control loop for sending velocity commands
  controller_frequency: 10.0

  # Trajectory Scoring Parameters
  meter_scoring: true # Assume goal and path distances are in metres
  path_distance_bias: 1.2 # Weighting for how much it should stick to the global path plan
  goal_distance_bias: 0.8 # Weighting for how much it should attempt to reach its local goal
  occdist_scale: 0.01 # Weighting for how much the controller should avoid obstacles

  heading_lookahead: 0.325
  heading_scoring: false
  heading_scoring_timestep: 1.0

  dwa: true # Try without due to poor acceleration constraints
  publish_cost_grid_pc: true

  # Oscillation Prevention Parameters
  oscillation_reset_dist: 0.025
  escape_reset_dist: 0.1
  escape_reset_theta: 0.1

  # Global Plan Parameters
  prune_plan: false
