local_costmap:
  global_frame: odom
  rolling_window: true
  track_unknown_space: false
  width: 5.0
  height: 5.0
  resolution: 0.025

  update_frequency: 5.0 # Map update frequency
  publish_frequency: 2.0 # Publish frequency

  plugins:
    - { name: obstacle_layer, type: "costmap_2d::ObstacleLayer" }
    - { name: inflation, type: "costmap_2d::InflationLayer" }
