local_costmap:
    global_frame:               odom
    rolling_window:             true
    track_unknown_space:        false
    width:                      5.0
    height:                     5.0
    origin_x:                   -2.5
    origin_y:                   -2.5
    resolution:                 0.05

    plugins:
      - {name: hokuyo_stvl,               type: "spatio_temporal_voxel_layer/SpatioTemporalVoxelLayer"}
      - {name: rgbd_obstacle_layer,       type: "spatio_temporal_voxel_layer/SpatioTemporalVoxelLayer"}
      - {name: inflation,                 type: "costmap_2d::InflationLayer"}

