robot_base_frame: base_link

transform_tolerance: 0.3 # Tolerable delay in transforms, s

# Footprint, metres
footprint: [[0.37, 0.28], [0.37, -0.28], [-0.37, -0.28], [-0.37, 0.28]]
footprint_padding: 0.05

# Update map with information about obstacles that are within m distance of the base
obstacle_range: 5
# Attempt to clear out space in front of base
raytrace_range: 5.5

obstacle_layer:
  observation_sources: scan
  scan:
    data_type: LaserScan
    topic: /vector/base_scan_filtered
    sensor_frame: base_link
    marking: true
    clearing: true
    min_obstacle_height: -1.0
    max_obstacle_height: 1.0
    expected_update_rate: 0.1
    observation_persistence: 0.0 # How long to keep each sensor reading (in seconds), 0.0 only keeps most recent
    inf_is_valid: true
    voxel_filter: false
    clear_after_reading: false

inflation:
  inflation_radius: 1.55
  cost_scaling_factor: 10

static_layer:
  map_topic: map
  subscribe_to_updates: true
